spring:
    application:
        name: store
stripe:
    apiUrl: https://api.stripe.com
    enabled: true
    timeout: 1000
    supported-currencies: HKD,USD
payment-gateway: stripe
emailServer:
    host: 127.0.0.1
    port: 8080