spring:
    application:
        name: store
    datasource:
      url: jdbc:mysql://localhost:3306/store?createDatabaseIfNotExist=true
      username: root
      password: ds26828784
stripe:
    apiUrl: https://api.stripe.com
    enabled: true
    timeout: 1000
    supported-currencies: HKD,USD
payment-gateway: stripe
emailServer:
    host: 127.0.0.1
    port: 8080